language: python

python:
    - "2.7"
    - "3.4"

services:
    - redis-server

install:
    - pip install -r requirements.txt

before_script:
    - psql -c 'create database twobuntu;' -U postgres

script:
    - cp twobuntu/local_settings.py.default twobuntu/local_settings.py
    - |
      echo "DATABASES = {
          'default': {
              'ENGINE': 'django.db.backends.postgresql_psycopg2',
              'NAME': 'twobuntu',
              'USER': 'postgres',
          },
      }
      CACHES = {
          'default': {
              'BACKEND': 'django_redis.cache.RedisCache',
              'LOCATION': 'redis://127.0.0.1:6379/0',
          },
      }
      SECRET_KEY = '1234567890abcdef'" >> twobuntu/local_settings.py
    - ./manage.py migrate --noinput
    - ./manage.py test --noinput
